import { DataLoadError, type DataProvider, type ReadModelManifest, type RecordDetail, type RecordEdge, type RecordSummary } from "./types";
import { isReadModelVersionCompatible } from "./readModelCompatibility";

/**
 * Record IDs are generated by the RE-01 adapter (schema prefix + opaque
 * suffix, e.g. "PRB-0005", "EVD-000105") and are never expected to contain
 * path separators. This is a generic, prefix-agnostic shape check — it does
 * not hardcode SRC-/EVD-/PRB- — so a future schema-conforming
 * record type's ID remains resolvable without a provider change.
 */
const SAFE_ID_PATTERN = /^[A-Za-z][A-Za-z0-9]*-[A-Za-z0-9]+$/;

function isSyntacticallySafeId(id: string): boolean {
  return (
    typeof id === "string" &&
    id.length > 0 &&
    id.length <= 128 &&
    !id.includes("/") &&
    !id.includes("\\") &&
    !id.includes("..") &&
    SAFE_ID_PATTERN.test(id)
  );
}

/**
 * All generated-data asset URLs are built here, and only here — no other
 * module in the application constructs a fetch path into `generated/`. Uses
 * `import.meta.env.BASE_URL` (always ends with "/") rather than a hardcoded
 * "/" so a future sub-path deployment (docs/explorerarchitecture.md) needs no
 * provider change, only a build-time `base` setting.
 */
function assetUrl(relativePath: string): string {
  return `${import.meta.env.BASE_URL}${relativePath}`;
}

async function fetchJson<T>(relativePath: string, describe: string): Promise<T> {
  let response: Response;
  try {
    response = await fetch(assetUrl(relativePath));
  } catch (cause) {
    throw new DataLoadError(
      `Não foi possível carregar ${describe}.`,
      "network"
    );
  }

  if (response.status === 404) {
    throw new DataLoadError(
      `Não foi possível encontrar ${describe}.`,
      "missing"
    );
  }
  if (!response.ok) {
    throw new DataLoadError(`Não foi possível carregar ${describe} (HTTP ${response.status} ${response.statusText}).`, "network");
  }

  try {
    return (await response.json()) as T;
  } catch (cause) {
    throw new DataLoadError(
      `Não foi possível interpretar ${describe}: formato JSON inválido.`,
      "malformed"
    );
  }
}

const REQUIRED_MANIFEST_STRING_FIELDS = ["readModelVersion", "generatedAt", "generator", "corpusFingerprint"] as const;

function assertManifestShape(data: unknown): asserts data is ReadModelManifest {
  if (typeof data !== "object" || data === null) {
    throw new DataLoadError("O ficheiro manifest.json tem um formato inválido.", "malformed");
  }
  const m = data as Record<string, unknown>;

  for (const field of REQUIRED_MANIFEST_STRING_FIELDS) {
    if (typeof m[field] !== "string" || (m[field] as string) === "") {
      throw new DataLoadError(`O ficheiro manifest.json tem um campo obrigatório em falta ou inválido: "${field}".`, "malformed");
    }
  }
  if (m.sourceCommit !== null && typeof m.sourceCommit !== "string") {
    throw new DataLoadError('O ficheiro manifest.json tem um campo inválido: "sourceCommit".', "malformed");
  }
  if (typeof m.totalRecords !== "number" || !Number.isFinite(m.totalRecords)) {
    throw new DataLoadError('O ficheiro manifest.json tem um campo inválido: "totalRecords".', "malformed");
  }
  if (typeof m.counts !== "object" || m.counts === null || Array.isArray(m.counts)) {
    throw new DataLoadError('O ficheiro manifest.json tem um campo inválido: "counts".', "malformed");
  }
  if (!Array.isArray(m.schemaPrefixes)) {
    throw new DataLoadError('O ficheiro manifest.json tem um campo inválido: "schemaPrefixes".', "malformed");
  }
}

function isObject(value: unknown): value is Record<string, unknown> {
  return typeof value === "object" && value !== null && !Array.isArray(value);
}

function isNonEmptyString(value: unknown): value is string {
  return typeof value === "string" && value.length > 0;
}

function isOrdinal(value: unknown): value is number | null {
  return value === null || (typeof value === "number" && Number.isInteger(value));
}

function assertIndexShape(data: unknown): asserts data is RecordSummary[] {
  if (!Array.isArray(data)) throw new DataLoadError("O ficheiro index.json tem um formato inválido.", "malformed");
  for (const item of data) {
    if (!isObject(item) || !isNonEmptyString(item.id) || !isNonEmptyString(item.type) || !isNonEmptyString(item.label) || !isNonEmptyString(item.file) || !isObject(item.summaryFields)) {
      throw new DataLoadError("O ficheiro index.json contém entradas incompletas.", "malformed");
    }
  }
}

function assertEdgeRefShape(value: unknown, direction: "incoming" | "outgoing"): void {
  if (!isObject(value) || !isNonEmptyString(value.field) || !isOrdinal(value.ordinal) || !isNonEmptyString(value[direction === "incoming" ? "from" : "to"])) {
    throw new DataLoadError("O detalhe do registo contém relações de entrada ou saída inválidas.", "malformed");
  }
}

function assertRecordDetailShape(data: unknown): asserts data is RecordDetail {
  if (!isObject(data) || !isNonEmptyString(data.id) || !isNonEmptyString(data.type) || !isNonEmptyString(data.file) || !isObject(data.record) || !Array.isArray(data.outgoingEdges) || !Array.isArray(data.incomingEdges)) {
    throw new DataLoadError("O detalhe do registo tem um formato inválido.", "malformed");
  }
  data.outgoingEdges.forEach((edge) => assertEdgeRefShape(edge, "outgoing"));
  data.incomingEdges.forEach((edge) => assertEdgeRefShape(edge, "incoming"));
}

function assertEdgesShape(data: unknown): asserts data is RecordEdge[] {
  if (!Array.isArray(data)) throw new DataLoadError("O ficheiro edges.json tem um formato inválido.", "malformed");
  for (const edge of data) {
    if (!isObject(edge) || !isNonEmptyString(edge.id) || !isNonEmptyString(edge.from) || !isNonEmptyString(edge.to) || !isNonEmptyString(edge.field) || !isOrdinal(edge.ordinal) || typeof edge.required !== "boolean") {
      throw new DataLoadError("O ficheiro edges.json contém relações incompletas.", "malformed");
    }
  }
}

/**
 * Consumes the RE-01 generated read model over HTTP as static JSON assets
 * (served from apps/research-explorer/generated/ via Vite's publicDir — see
 * vite.config.ts). Validates manifest shape and readModelVersion
 * compatibility before returning anything to the caller; never returns
 * partially-interpreted data.
 *
 * Deliberately does not load edges.json or any record-detail file eagerly —
 * getRecord() is provided for RE-02B and safe to call now, but nothing in
 * RE-02A's application startup calls it.
 */
export class StaticDataProvider implements DataProvider {
  private manifestPromise: Promise<ReadModelManifest> | null = null;
  private indexPromise: Promise<RecordSummary[]> | null = null;
  private edgesPromise: Promise<RecordEdge[]> | null = null;

  async getManifest(): Promise<ReadModelManifest> {
    if (!this.manifestPromise) {
      this.manifestPromise = this.loadManifest().catch((error: unknown) => {
        // Do not cache a rejected load: a transient network failure should
        // not permanently poison retries.
        this.manifestPromise = null;
        throw error;
      });
    }
    return this.manifestPromise;
  }

  private async loadManifest(): Promise<ReadModelManifest> {
    const data = await fetchJson<unknown>("manifest.json", "o manifesto do Explorer");
    assertManifestShape(data);

    if (!isReadModelVersionCompatible(data.readModelVersion)) {
      throw new DataLoadError(
        `A versão "${data.readModelVersion}" dos dados gerados não é compatível com esta versão do Explorer.`,
        "incompatible"
      );
    }

    return data;
  }

  async listRecords(): Promise<RecordSummary[]> {
    if (!this.indexPromise) {
    this.indexPromise = fetchJson<unknown>("index.json", "o índice de registos do Explorer")
        .then((data) => {
          assertIndexShape(data);
          return data;
        })
        .catch((error: unknown) => {
          this.indexPromise = null;
          throw error;
        });
    }
    return this.indexPromise;
  }

  async getRecord(id: string): Promise<RecordDetail> {
    if (!isSyntacticallySafeId(id)) {
      throw new DataLoadError(`"${id}" não é um identificador de registo válido.`, "invalid_id");
    }

    // Never fetch a record-detail path for an ID that isn't part of the
    // generated index, even if it is syntactically well-formed — this is the
    // "part of the known record set" check, not just a shape check.
    const index = await this.listRecords();
    const known = index.some((r) => r.id === id);
    if (!known) {
      throw new DataLoadError(`O registo "${id}" não foi encontrado.`, "not_found");
    }

    const detail = await fetchJson<unknown>(`record-detail/${encodeURIComponent(id)}.json`, `o detalhe do registo «${id}»`);
    assertRecordDetailShape(detail);
    return detail;
  }

  /**
   * Loads edges.json on first call and caches the result — never invoked by
   * anything except the Graph view (RE-04), so a session that never opens
   * Graph never fetches it (D7: neighbourhood mode over the full graph).
   */
  async getEdges(): Promise<RecordEdge[]> {
    if (!this.edgesPromise) {
      this.edgesPromise = fetchJson<unknown>("edges.json", "o conjunto de relações do Explorer")
        .then((data) => {
          assertEdgesShape(data);
          return data;
        })
        .catch((error: unknown) => {
          this.edgesPromise = null;
          throw error;
        });
    }
    return this.edgesPromise;
  }
}
